### ISSUE TITLE
Question: Are AWS Spot Instances Possible?

### ISSUE THREAD

**Issue by joshes** [clusterinthecloud/support#18]
Hello. I'm curious if it's possible to configure the CITC automation to utilize AWS Spot Instances? I'm looking to A) confirm it's possible or not and B) some direction as to where I would configure this functionality.

If there's a better place for these types of questions, please LMK.

Thanks.

**Comment by milliams** [comment]
Currently it is not possible. However, we are planning a hackathon in December where we are hoping to add this functionality so a version of it should be available by the end of the year.

**Comment by joshes** [comment]
That's great, I'll keep an eye out.
