### ISSUE TITLE
Turn off Hyper-Threading

### ISSUE THREAD

**Issue by trnh** [clusterinthecloud/support#9]
I am trying to find a way to run a post installation script to turn off HT like this

for cpunum in $(cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list | cut -s -d, -f2- | tr ',' '\n' | sort -un)
do
                echo 0 > /sys/devices/system/cpu/cpu$cpunum/online
done

is there anyway to turn HT off.

**Comment by milliams** [comment]
I'm assuming that you only care about this on the compute nodes, not on the login node?

Currently we only have hooks into customising the image, not into running a post-boot script. That said, it's not a hard change to make. I've added a issue at clusterinthecloud/ansible#83 to track this.

I'm hoping to track down some of these quality-of-life issues over the summer to make these things easier.

For a quick hack, you can add it into the bottom of the script at `/home/slurm/bootstrap.sh` which should be run on all newly-booted nodes.

The only potential issue would be that Slurm expects a certain number of cores per instance type and so there might need to be a tweak elsewhere too.

**Comment by trnh** [comment]
bootstrap.sh solution should work fine , the reason to turn off HT on AWS for MPI application to use physcal core.

Thank you
